In [1]:
import numpy as np
import pandas as pd
import importlib
import time
import matplotlib.pyplot as plt
import redis
import dask.dataframe as dd

from numpy.linalg import norm
from sklearn.model_selection import train_test_split

import NearestNeighbour as nn
import NearestNeighbour2 as nn2
import NearestNeighbour3 as nn3

In [2]:
path = "C:/Users/KennethOng/Documents/GitHub/ITI105-Project-Team4/Data/ratings.csv"

In [3]:
df = pd.read_csv(path)

In [4]:
df.shape

(26024289, 4)

In [5]:
df_train, df_test = train_test_split(df, test_size=0.3, random_state=42)

In [59]:
df_train.to_csv('ratings_train.csv')

In [60]:
df_test.to_csv('ratings_test.csv')

In [22]:
df_test

          userId  movieId  rating   timestamp
11928665  123687      163     4.0  1259948252
13042387  135533    55118     4.5  1451620634
70325        741     3499     4.0  1247359351
16382007  170293     2571     3.0  1438244027
21293077  221195     4973     4.0  1465065341
...          ...      ...     ...         ...
6488575    66987    82459     4.0  1433584511
1255591    12853     2424     3.0   981708465
23689136  245865     1608     3.0   944959510
8899925    91812       47     3.0   867757912
2639255    27409   148956     2.0  1484837791

[7807287 rows x 4 columns]

In [36]:
importlib.reload(nn2)
importlib.reload(nn21)

In [61]:
nearestNeighbour = nn2.NearestNeighbour(df_train)

A modification have been done on the NearPy library. The original library includes the original vector (which is normalized) in the hashtable. Due to the fact for recommender systems where each vector consist of a large number of columns (in this dataset >45k columns. Even after converting to a dense vector, it still causes memory issues), the resulting hashtable is large enough to cause memory issues (at least with my PC). The library is modified so that the vectors are not stored. The drawback is that distances cannot be calculated in query function. That have also been removed. The whole list of candidates will be returned. The vectors and therefore the distance and the rankings will be retrieved/calculated afterwards.

In [15]:
names = ['Scaled','Scaled03','Scaled07','Scaled13','Scaled17','Scaled23','Scaled27','Scaled33','Scaled37','Scaled43']
rseeds = [42,3,7,13,17,23,27,33,37,43]
hashdic = {}
hashdic = dict(zip(names,rseeds))
hashdic['Scaled03']

3

In [32]:
names = ['Scaled','Scaled03','Scaled07','Scaled13','Scaled17']
rseeds = [42,3,7,13,17]
hashdic2 = {}
hashdic2 = dict(zip(names,rseeds))
hashdic2['Scaled03']

3

In [6]:
import NearestNeighbour31 as nn31

In [35]:
import NearestNeighbour21 as nn21

In [20]:
importlib.reload(nn21)

In [14]:
#Running predictions for 1 hashtable, with n users/items
start = time.time()

nearestNeighbour = nn2.NearestNeighbour(df_train)
nearestNeighbour.approxSimilaritiesFit('Scaled83',randomSeed=3);
dictionary = nearestNeighbour.generateNeighbours(df_test,24)
nnMP = nn21.NearestNeighbour(df_train,dictionary)

grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2= nnMP.calculateScore2(df_test,24)
end = time.time()
print(end - start)
print(grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2)

No. of users in list:  268943
[39520, 136048, 160324, 159366, 51478, 163827, 11392, 10461, 111437, 183337, 206164, 63360, 211846, 38188, 79083, 183263, 262537, 57363, 209474, 150462, 225328, 88090, 253343, 98762]
Starting MP
movie not in original list
148.2600758075714
334.3439411737752 265.61125626790397 339 417 5691.343941173776 1685.6112562679045 756

In [45]:
importlib.reload(nn31)

In [16]:
#Running prediction for 1 hashtable
start = time.time()

nearestNeighbour = nn3.NearestNeighbour(df_train)
nearestNeighbour.approxSimilaritiesFit('Scaled28',randomSeed=42);
dictionary = nearestNeighbour.generateNeighbours(df_test,12)
nnMP = nn31.NearestNeighbour(df_train,dictionary)

grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2= nnMP.calculateScore2(df_test,12)
end = time.time()
print(end - start)
print(grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2)

No. of movies in list:  42231
no movie in database
[6266, 106147, 105034, 3917, 111249, 91770, 146074, 143178, 81823, 72605, 169606]
Starting MP
Starting score calculations
1256.78507065773
1151.353305290553 766.235792033637 955 617 8768.853305290555 2830.235792033637 1572

In [52]:
importlib.reload(nn21)

In [17]:
redisnames = ['Scaled28', 'Scaled2803', 'Scaled2807', 'Scaled2813', 'Scaled2817', 'Scaled2823', 'Scaled2827', 'Scaled2833', 'Scaled2837', 'Scaled2843']
randomseeds = [42,3,7,13,17,23,27,33,37,43]

hashdic = {}
hashdic = dict(zip(redisnames,randomseeds))

In [43]:
redisnames = ['Scaled2823', 'Scaled2827', 'Scaled2833', 'Scaled2837', 'Scaled2843']
randomseeds = [23,27,33,37,43]

hashdic3 = {}
hashdic3 = dict(zip(redisnames,randomseeds))

In [24]:
redisnames = ['Scaled28', 'Scaled2803', 'Scaled2807', 'Scaled2813', 'Scaled2817']
randomseeds = [42,3,7,13,17]

hashdic2 = {}
hashdic2 = dict(zip(redisnames,randomseeds))
hashdic2

{'Scaled28': 42,
 'Scaled2803': 3,
 'Scaled2807': 7,
 'Scaled2813': 13,
 'Scaled2817': 17}

In [55]:
start = time.time()

dictionary = {}
i=0
for key in hashdic2.keys():
    print(key)
    nearestNeighbour = nn2.NearestNeighbour(df_train)
    nearestNeighbour.approxSimilaritiesFit(key, randomSeed=hashdic2[key]);
    
    dic = nearestNeighbour.generateNeighbours(df_test,10)
    
    if i ==0:
        dictionary = dic
        i = 1
    else:
        for item in dic.keys():
            list1=dic[item]
            list2=dictionary[item]
            l = set(list1+list2)
            dictionary[item]=list(l)


nnMP = nn21.NearestNeighbour(df_train,dictionary)
grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2= nnMP.calculateScore2(df_test,10)
# ratings = nnMP.calculateScore2(df_test,10)
print(grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2)
    
end = time.time()
print(end - start)

Scaled
No. of users in list:  268943
Scaled03
No. of users in list:  268943
Scaled07
No. of users in list:  268943
Scaled13
No. of users in list:  268943
Scaled17
No. of users in list:  268943
[6275, 129506, 237908, 264940, 148013, 84780, 448, 136115, 251851, 259223]
             0  user
0     1.000000     0
1     1.000000     1
2     1.000000     2
3     1.000000     3
4     1.000000     4
...        ...   ...
1050  1.000000  1050
1051  1.000000  1051
1052  1.000000  1052
1053  0.955587  1053
1054  0.000000  1054

[1055 rows x 2 columns]
             0  user
0     1.000000     0
1     1.000000     1
2     0.973589     2
3     1.000000     3
4     1.000000     4
...        ...   ...
1158  1.000000  1158
1159  1.000000  1159
1160  1.000000  1160
1161  1.000000  1161
1162  0.000000  1162

[1163 rows x 2 columns]
             0  user
0     0.974532     0
1     1.000000     1
2     1.000000     2
3     0.954444     3
4     1.072436     4
...        ...   ...
1614  1.000000  1614
1615  1.000000  1615
1616  0.952180  1616
1617  0.881816  1617
1618  0.000000  1618

[1619 rows x 2 columns]
             0  user
0     1.000000     0
1     1.000000     1
2     1.045894     2
3     1.000000     3
4     0.988386     4
...        ...   ...
1464  1.000000  1464
1465  0.963255  1465
1466  1.000000  1466
1467  0.970408  1467
1468  0.000000  1468

[1469 rows x 2 columns]
             0  user
0     0.894033     0
1     0.985681     1
2     0.972043     2
3     1.000000     3
4     1.000000     4
...        ...   ...
1570  0.993269  1570
1571  1.000000  1571
1572  1.000000  1572
1573  1.014228  1573
1574  0.000000  1574

[1575 rows x 2 columns]
             0  user
0     0.978198     0
1     0.930175     1
2     1.000000     2
3     1.001600     3
4     1.000000     4
...        ...   ...
1194  0.985551  1194
1195  1.000874  1195
1196  1.000000  1196
1197  0.973895  1197
1198  0.000000  1198

[1199 rows x 2 columns]
             0  user
0     1.000000     0
1     1.001613     1
2     1.009238     2
3     0.999400     3
4     0.981458     4
...        ...   ...
1529  1.011550  1529
1530  1.009601  1530
1531  1.012013  1531
1532  0.999913  1532
1533  0.000000  1533

[1534 rows x 2 columns]
             0  user
0     1.000000     0
1     1.035205     1
2     0.969008     2
3     1.000000     3
4     0.987147     4
...        ...   ...
1623  1.000000  1623
1624  1.000000  1624
1625  1.000000  1625
1626  1.006855  1626
1627  0.000000  1627

[1628 rows x 2 columns]
             0  user
0     1.000000     0
1     0.927346     1
2     1.002056     2
3     0.830230     3
4     0.989064     4
...        ...   ...
1170  0.865020  1170
1171  1.000000  1171
1172  1.000000  1172
1173  0.968554  1173
1174  0.000000  1174

[1175 rows x 2 columns]
             0  user
0     0.994027     0
1     0.995803     1
2     1.000000     2
3     1.000000     3
4     0.994189     4
...        ...   ...
1327  1.000000  1327
1328  1.000000  1328
1329  1.006867  1329
1330  1.000000  1330
1331  0.000000  1331

[1332 rows x 2 columns]
85.02768343438322 67.93798854326297 91 32 543.0276834343833 183.937988543263 123
1006.1530952453613

In [31]:
start = time.time()

dictionary = {}
i=0
for key in hashdic2.keys():
    print(key)
    nearestNeighbour = nn3.NearestNeighbour(df_train)
    nearestNeighbour.approxSimilaritiesFit(key, randomSeed=hashdic2[key]);
    
    dic = nearestNeighbour.generateNeighbours(df_test,50)
    
    if i ==0:
        dictionary = dic
        i = 1
    else:
        for item in dic.keys():
            list1=dic[item]
            list2=dictionary[item]
            l = set(list1+list2)
            dictionary[item]=list(l)


nnMP = nn31.NearestNeighbour(df_train,dictionary)
grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2= nnMP.calculateScore2(df_test,50)

print(grandtotalMSE, grandtotalMAE, grandlength, grandnorec, grandtotalMSE2, grandtotalMAE2, grandlength2)
    
end = time.time()
print(end - start)

Scaled28
No. of movies in list:  42231
no movie in database
no movie in database
Scaled2803
No. of movies in list:  42231
no movie in database
no movie in database
Scaled2807
No. of movies in list:  42231
no movie in database
no movie in database
Scaled2813
No. of movies in list:  42231
no movie in database
no movie in database
Scaled2817
No. of movies in list:  42231
no movie in database
no movie in database
[7389, 113503, 117881, 87170, 88672, 2922, 3236, 173353, 2820, 4429, 1106, 142204, 122747, 165415, 92910, 5375, 2127, 115604, 166474, 90239, 73922, 160080, 143103, 153650, 86760, 80858, 170213, 116807, 4197, 138460, 1002, 7624, 70846, 153200, 134587, 2981, 3433, 72731, 1713, 126975, 30981, 26745, 139783, 7178, 982, 160201, 88839, 174055]
Starting MP
Starting score calculations
2439.3295162500303 1741.9616613967019 2285 1633 21106.579516250033 6941.461661396702 3918
6466.33454990387

In [14]:
candidates = nearestNeighbour.approxSimilaritiesPredict(99427)
candidates

[189383,
 263596,
 19907,
 196510,
 245478,
 132062,
 190989,
 112584,
 154532,
 101737,
 73500,
 222072,
 163510,
 254535,
 20899,
 90889,
 218605,
 229643,
 99212,
 118557,
 130886,
 245411,
 25808,
 261586,
 122948,
 26081,
 230417,
 91382,
 5351,
 149063,
 36045,
 110071,
 205791,
 63805,
 32769,
 176240,
 171091,
 179383,
 141870,
 241513,
 100941,
 87545,
 152333,
 178963,
 133301,
 250490,
 126498,
 114037,
 62902,
 203968,
 225575,
 176293,
 199065,
 32139,
 161631,
 248909,
 23320,
 184037,
 75660,
 72549,
 137632,
 172038,
 225233,
 141248,
 64644,
 178056,
 49794,
 123833,
 199666,
 242374,
 127986,
 62397,
 237580,
 224823,
 4979,
 245596,
 231990,
 197288,
 232431,
 54198,
 18791,
 213360,
 26256,
 36494,
 36483,
 128644,
 258943,
 70366,
 57623,
 99228,
 238114,
 128639,
 256341,
 116636,
 99291,
 172482,
 159561,
 90961,
 234527,
 137077,
 60669,
 192082,
 230317,
 189763,
 21494,
 127996,
 84879,
 206172,
 114512,
 44210,
 184689,
 176140,
 112871,
 214328,
 165831,
 124432,
 174171,
 99427,
 107299,
 196399,
 14735,
 23821,
 256966,
 258991,
 243919,
 119216,
 50661,
 212382,
 233274,
 199654,
 162068,
 203369,
 190739,
 183780,
 224602,
 57095,
 65654,
 173244,
 21642,
 238499,
 208774,
 190490,
 184700,
 233924,
 129640,
 30696,
 163197,
 19243,
 254585,
 36402,
 251103,
 206553,
 221973,
 39589,
 206366,
 13531,
 178007,
 166323,
 32149,
 183610,
 202085,
 99663,
 41310,
 181745,
 66864,
 7178,
 61927,
 235114,
 201954,
 90717,
 134219,
 83393,
 144838,
 211716,
 15245,
 172511,
 114107,
 31686,
 7467,
 92118,
 216624,
 221094,
 62109,
 85479,
 118371,
 8296,
 200615,
 38049,
 188223,
 98010,
 197409,
 18258,
 20623,
 266546,
 177292,
 31591,
 15660,
 79563,
 206352,
 193810,
 262950,
 263985,
 52144,
 103177,
 215830,
 182223,
 33115,
 186288,
 238124,
 97887,
 213120,
 43568,
 183699,
 109203,
 87113,
 82927,
 102836,
 93404,
 226456,
 179207,
 267478,
 50375,
 126456,
 183397,
 82817,
 104886,
 120184,
 13891,
 111318,
 263350,
 205200,
 111989,
 78380,
 174523,
 250884,
 245780,
 89825,
 264375,
 222171,
 147837,
 110361,
 136162,
 220001,
 171763,
 140953,
 257701,
 23957,
 169681,
 101205,
 172841,
 56476,
 247570,
 136843,
 132502,
 167037,
 188376,
 51255,
 38139,
 191927,
 60879,
 200752,
 166961,
 256429,
 86475,
 62619,
 40369,
 90743,
 207583,
 31630,
 203077,
 62229,
 126809,
 32483,
 237009,
 189206,
 130667,
 170281,
 13627,
 111233,
 47646,
 5650,
 199930,
 33589,
 263978,
 224053,
 115404,
 128821,
 52608,
 96023,
 49909,
 108739,
 182789,
 240853,
 251677,
 157219,
 134169,
 223285,
 179713,
 228105,
 47105,
 1265,
 141732,
 24770,
 258753,
 112920,
 232100,
 229465,
 233221,
 199433,
 167366,
 71507,
 193851,
 253890,
 98670,
 110134,
 90783,
 142961,
 225569,
 245282,
 263754,
 149833,
 63085,
 217750,
 156578,
 143550,
 73487,
 123479,
 32399,
 110148,
 159195,
 18106,
 126516,
 189961,
 219116,
 61584,
 262251,
 233261,
 43161,
 34957,
 74948,
 228250,
 263511,
 221270,
 64713,
 71576,
 102903,
 246459,
 26531,
 26013,
 235651,
 119843,
 254705,
 3000,
 35456,
 60368,
 253372,
 137801,
 100050,
 84784,
 120353,
 220697,
 191719,
 144079,
 11732,
 152951,
 250029,
 37375,
 148043,
 139866,
 117505,
 126264,
 258343,
 185175,
 254311,
 15392,
 42209,
 251510,
 121257,
 52687,
 172951,
 68648,
 56131,
 232253,
 130975,
 27715,
 172331,
 234247,
 50805,
 97644,
 205565,
 241589,
 182105,
 233198,
 175415,
 200051,
 30581,
 235486,
 109827,
 15109,
 125322,
 75166,
 102452,
 134016,
 107951,
 27504,
 1230,
 184680,
 212387,
 237549,
 217625,
 196162,
 198648,
 79582,
 119977,
 55557,
 268726,
 175599,
 38028,
 167888,
 150771,
 34157,
 6280,
 105711,
 116508,
 60612,
 50290,
 168910,
 259442,
 8544,
 56622,
 166386,
 207016,
 220075,
 72564,
 258636,
 133270,
 82630,
 6864,
 147724,
 143774,
 3944,
 188667,
 100611,
 91836,
 229772,
 51695,
 204743,
 269672]

In [53]:
recommendations = nearestNeighbour.recommendations(candidates,99427)
recommendations

            0  user
0    1.000000     0
1    1.000000     1
2    1.000000     2
3    1.000000     3
4    0.911710     4
..        ...   ...
443  0.552786   443
444  1.000000   444
445  1.000000   445
446  1.000000   446
447  0.000000   447

[448 rows x 2 columns]

92259     2.492027
174055    2.433353
104879    2.242027
88125     2.242027
57528     2.242027
96821     2.242027
33660     2.134390
55995     2.086795
37240     2.086795
72720     2.081682
dtype: float64